#!/bin/bash

echo ""
echo " /\$\$\$\$\$\$\$                                                  "
echo "| \$\$__  \$\$                                                 "
echo "| \$\$  \ \$\$ /\$\$\$\$\$\$   /\$\$\$\$\$\$   /\$\$\$\$\$\$   /\$\$\$\$\$\$   /\$\$\$\$\$\$ "
echo "| \$\$\$\$\$\$\$//\$\$__  \$\$ /\$\$__  \$\$ /\$\$__  \$\$ /\$\$__  \$\$ /\$\$__  \$\$"
echo "| \$\$____/| \$\$\$\$\$\$\$\$| \$\$\$\$\$\$\$\$| \$\$  \ \$\$| \$\$\$\$\$\$\$\$| \$\$  \__/"
echo "| \$\$     | \$\$_____/| \$\$_____/| \$\$  | \$\$| \$\$_____/| \$\$      "
echo "| \$\$     |  \$\$\$\$\$\$\$|  \$\$\$\$\$\$\$| \$\$\$\$\$\$\$/|  \$\$\$\$\$\$\$| \$\$      "
echo "|__/      \_______/ \_______/| \$\$____/  \_______/|__/      "
echo "                             | \$\$                          "
echo "                             | \$\$                          "
echo "                             |__/                          "
echo ""
echo -e "\e[36m----------------------------------------\e[0m"
echo -e "\e[1;32mWelcome to Peeper\e[0m, the \e[1;34moperating system for your data\e[0m."
echo -e "Visit \e[1;36mhttps://github.com/climactic/peeper\e[0m to learn more about Peeper."
echo -e "If you find Peeper useful, please consider supporting the project by giving it a \e[1;33mstar on GitHub\e[0m or \e[1;35mSponsoring\e[0m!"
echo -e "Website: \e[1;36mhttps://peeper.dev\e[0m"
echo -e "\e[36m----------------------------------------\e[0m"
